### ISSUE TITLE
utf8.find not working on android in russian

### ISSUE THREAD

**Issue by jalomic** [starwing/luautf8#11]
local test_remove = "АБВГДИКЛМНОПРСТ"
    local remove_word = "ГДИК"
local word_start, word_end = utf8.find(test_remove, remove_word,1, true)
--word_start and word_end are nil

on Mac OS all OK

**Comment by starwing** [comment]
okay, I will look into this issue :)

**Comment by starwing** [comment]
p.s. your script file should in UTF-8 encoded, can you offer a file for test? thanks :)

**Comment by SDraw** [comment]
Checked with CP-1251 and UTF-8 encoding, no problems have occured.

**Comment by starwing** [comment]
I have not android environment, but in my macOS it seems all right. maybe you should check whether the source file is in UTF-8 encode first?

**Comment by jalomic** [comment]
Checked on windows and mac os, no problem no problems have occured too =) but damn android !

**Comment by starwing** [comment]
but why? I use the charset that parsed from Unicode Database, not specified by any system. it impossible working on Desktop but not on mobile :-(

can you give Android test case (apk file and source text file in assets of ask) and I have a try?

you could make a apk, read file in assets, and use lua-utf8 to show the result, and I could replace this file to see difference.
