### ISSUE TITLE
utf8.remove no arguments doesn't work

### ISSUE THREAD

**Issue by vadi2** [starwing/luautf8#12]
###utf8.remove(s[, start[, stop]]) -> new_string
delete a substring in s. If neither start nor stop is given, delete the
last UTF-8 char in s

```lua
> print(utf8.remove("мясо"))
stdin:1: bad argument #2 to 'remove' (number expected, got no value)
stack traceback:
	[C]: in function 'remove'
```

**Comment by SDraw** [comment]
Possible typo in readme, because utf8.remove needs second argument
https://github.com/starwing/luautf8/blob/master/lutf8lib.c#L497
If replace this line with
```Cpp
luaL_optinteger(L, 2, 1), luaL_optinteger(L, 3, -1)))
```
it will work as in readme descriptoin.

**Comment by starwing** [comment]
Good catch! Thanks for report. I'm busy for work recently. But I will look into this as soon as possible.
