### ISSUE TITLE
utf8.len() never return false when UTF8 has an invalid sequence

### ISSUE THREAD

**Issue by cvuillemez** [starwing/luautf8#13]
Hi,
I want to use utf8.len() on lua 5.1 to validate a UTF8 sequence but it does not do the job.

When I put a good sequence:
```
> s = '\207\180'
> len, inv = utf8.len(s)
> print(len, inv)
1       nil
> print(utf8.codepoint(s,1,-1))
1012
```

.. function works as expected, it prints the right codepoint and length, but when I put an invalid sequence:

```
> s = '\255\180'
> len, inv = utf8.len(s)
> print(len, inv)
2       nil
> print(utf8.codepoint(s,1,-1))
510     180
```

.. i t does not return the `false` value and the position of the first invalid byte, like explained [here](https://www.lua.org/manual/5.3/manual.html#6.5)
Or maybe this module does not implement utf8 support like LUA 5.3 ?

Thanks.

**Comment by johnd0e** [comment]
@starwing

Why have you closed this issue?
Is it resolved?

**Comment by starwing** [comment]
Yes, I fixed at HEAD
