### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [starwing/luautf8#16]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for luautf8. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by alerque** [comment]
This is not necessary. Yes there used to be issues with `git archive` not being stable, but both the Git project and GitHub worked pretty hard to address this and for projects that have no other need for a true source release (i.e. generated sources), the output is stable enough for release.
