### ISSUE TITLE
Access violation in multithreaded app

### ISSUE THREAD

**Issue by rinart73** [starwing/luautf8#18]
I'm trying to use your dll (which I sucessfully compiled) in multithreaded C/C++/Lua app. And I'm getting Access violation error.
I'm new to this, so my question is: Does your dll supports this? Is there a way to fix this error?

**Comment by starwing** [comment]
Do you have a test case to show it? It seems that I don't change any global variables. So this dll shouldn't produce a crash.

**Comment by starwing** [comment]
close as no further reply
