### ISSUE TITLE
parseucd.lua is incompatible with lua 5.1

### ISSUE THREAD

**Issue by SlySven** [starwing/luautf8#23]
Unfortunately line 74 of `parseucd.lua` uses the `goto` command. :scream:

This *feature* :roll_eyes: was only introduced in Lua 5.**2** so is not supported by 5.1 ...

This is awkward because the `unidata.h` file is likely to be way out of date by now - the last commit to touch it was entitled "update UCD to 8.0.0" and Unicode is currently at **12.1.0** - importantly some codepoints changed their width in Unicode 9 and I am suspecting this is affecting my project (with an embedded lua interpreted which is fixed to Lua 5.1) and I want to ensure all parts are using the same reference data...

**Comment by starwing** [comment]
you just build a Lua5.2 and run it for once. It's not designed for run in your project, but just generate .c files.

I will make a update for this

**Comment by SlySven** [comment]
Ah, I have done so with a bit of a negation of the conditions for some `if` s... I will put it up as a PR shortly - and it does make some changes to the `unidata.h` file for the later Unicode data (at **12.1.0**).

I note that there are multiple [`luarocks`](https://luarocks.org) *rockspec* files and whilst yours ([`luautf8`](https://luarocks.org/modules/xavier-wang/luautf8)) do correctly link to the correct commits in the Git repository, those of **Dan Note** ([`utf8`](https://luarocks.org/modules/dannote/utf8)) incorrectly point to the base repository URL and so  (AFAICT) they all pull in the `master` branch which represents your work as it was at the end of 2014!
