### ISSUE TITLE
Is there a next release schedule for luautf8 ?

### ISSUE THREAD

**Issue by komainu8** [starwing/luautf8#31]
Hello,

luautf8 of the current version occurs compile error on CentOS6.
This problem had already resolved by 1c3148d5c6014222d361309aa88a7302331756ea.
However, there is not a release version that includes this commit yet.

Would you tell me when you will release the next version?

Thanks,

**Comment by starwing** [comment]
Okay, I will make a new release for that.

**Comment by starwing** [comment]
the new release landed.

**Comment by komainu8** [comment]
Thank you very much!
