### ISSUE TITLE
lutf8.so: undefined symbol: luaL_checkint

### ISSUE THREAD

**Issue by ivopivo** [starwing/luautf8#5]
Hello Xavier

I'm using lua 5.3 and luarocks 2.2.2 both compiled from sources. After installing lutf8 from sources and requiring it into my lua sources I'm getting the following error:

lutf8.so: undefined symbol: luaL_checkint

utf8 module was built from this rock src
https://luarocks.org/manifests/xavier-wang/lutf8-0.1-1.src.rock

I.

**Comment by starwing** [comment]
I just changed the rock name and make a release, So you can try it:

```
luarocks install luautf8
```

to install the 0.1.0-1 version of lua-utf8.dll/so

**Comment by ivopivo** [comment]
Now it's working, thank you :)
