### ISSUE TITLE
match failing

### ISSUE THREAD

**Issue by aryajur** [starwing/luautf8#8]
```
ut = require("lua-utf8")
print(ut.match("北京奥贝克电子股份有限公司（补证）",".-%(.-%)%s*$"))   -- Returns nil
print(string.match("Absadlhsfjh (jas) ",".-%(.-%)%s*$"))   -- Returns Absadlhsfjh (jas)
```

**Comment by starwing** [comment]
the first one, you used full width char which isn't half width char you want match
second is right, you matched whole thing, and doesnt use capture.

**Comment by aryajur** [comment]
Thanks you are right, just visually looked similar.
